"""analytical schema

Revision ID: 0002_analytical_schema
Revises: 0001_baseline
Create Date: 2026-08-27 15:53:34.149582
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002_analytical_schema"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_competition",
        sa.Column("competition_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("tier", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("competition_id", name=op.f("pk_dim_competition")),
    )
    op.create_index("ix_dim_competition_country", "dim_competition", ["country"], unique=False)
    op.create_table(
        "dim_season",
        sa.Column("season_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=False),
        sa.Column("end_year", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "end_year >= start_year", name=op.f("ck_dim_season_season_years_ordered")
        ),
        sa.PrimaryKeyConstraint("season_id", name=op.f("pk_dim_season")),
    )
    op.create_table(
        "fact_data_quality",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("check_name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("record_count", sa.BigInteger(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "executed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pass', 'warn', 'fail')",
            name=op.f("ck_fact_data_quality_data_quality_status_valid"),
        ),
        sa.CheckConstraint(
            "record_count >= 0", name=op.f("ck_fact_data_quality_data_quality_count_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_data_quality")),
    )
    op.create_index("ix_data_quality_executed", "fact_data_quality", ["executed_at"], unique=False)
    op.create_table(
        "dim_club",
        sa.Column("club_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("competition_id", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["dim_competition.competition_id"],
            name=op.f("fk_dim_club_competition_id_dim_competition"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("club_id", name=op.f("pk_dim_club")),
    )
    op.create_index("ix_dim_club_competition", "dim_club", ["competition_id"], unique=False)
    op.create_index("ix_dim_club_name", "dim_club", ["name"], unique=False)
    op.create_table(
        "dim_player",
        sa.Column("player_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("nationality", sa.Text(), nullable=True),
        sa.Column("secondary_nationality", sa.Text(), nullable=True),
        sa.Column(
            "preferred_foot",
            sa.Enum("left", "right", "both", name="preferred_foot", native_enum=False),
            nullable=True,
        ),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column("raw_position", sa.String(length=64), nullable=True),
        sa.Column(
            "position_group",
            sa.Enum(
                "GK",
                "CB",
                "FB_WB",
                "DM",
                "CM",
                "AM",
                "WINGER",
                "FORWARD",
                name="position_group",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("current_club_id", sa.String(length=64), nullable=True),
        sa.Column("current_competition_id", sa.String(length=64), nullable=True),
        sa.Column("current_market_value_eur", sa.BigInteger(), nullable=True),
        sa.Column("contract_expires", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "date_of_birth IS NULL OR date_of_birth > DATE '1900-01-01'",
            name=op.f("ck_dim_player_date_of_birth_plausible"),
        ),
        sa.CheckConstraint(
            "current_market_value_eur IS NULL OR current_market_value_eur >= 0",
            name=op.f("ck_dim_player_market_value_non_negative"),
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR (height_cm BETWEEN 140 AND 220)",
            name=op.f("ck_dim_player_height_plausible"),
        ),
        sa.ForeignKeyConstraint(
            ["current_club_id"],
            ["dim_club.club_id"],
            name=op.f("fk_dim_player_current_club_id_dim_club"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["current_competition_id"],
            ["dim_competition.competition_id"],
            name=op.f("fk_dim_player_current_competition_id_dim_competition"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("player_id", name=op.f("pk_dim_player")),
    )
    op.create_index("ix_dim_player_club", "dim_player", ["current_club_id"], unique=False)
    op.create_index(
        "ix_dim_player_competition", "dim_player", ["current_competition_id"], unique=False
    )
    op.create_index("ix_dim_player_dob", "dim_player", ["date_of_birth"], unique=False)
    op.create_index(
        "ix_dim_player_market_value", "dim_player", ["current_market_value_eur"], unique=False
    )
    op.create_index(
        "ix_dim_player_normalized_name", "dim_player", ["normalized_name"], unique=False
    )
    op.create_index("ix_dim_player_position_group", "dim_player", ["position_group"], unique=False)
    op.create_index(
        "ix_dim_player_recruitment",
        "dim_player",
        ["position_group", "date_of_birth", "current_market_value_eur"],
        unique=False,
    )
    op.create_table(
        "bridge_player_source",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_player_id", sa.String(length=64), nullable=False),
        sa.Column("match_method", sa.String(length=64), nullable=False),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column("manual_override", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "match_confidence BETWEEN 0 AND 1",
            name=op.f("ck_bridge_player_source_match_confidence_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["dim_player.player_id"],
            name=op.f("fk_bridge_player_source_player_id_dim_player"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bridge_player_source")),
        sa.UniqueConstraint("source", "source_player_id", name="uq_bridge_source_id"),
    )
    op.create_index("ix_bridge_player", "bridge_player_source", ["player_id"], unique=False)
    op.create_table(
        "fact_market_value",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("valued_on", sa.Date(), nullable=False),
        sa.Column("market_value_eur", sa.BigInteger(), nullable=False),
        sa.Column("club_id", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "market_value_eur >= 0", name=op.f("ck_fact_market_value_market_value_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["dim_club.club_id"],
            name=op.f("fk_fact_market_value_club_id_dim_club"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["dim_player.player_id"],
            name=op.f("fk_fact_market_value_player_id_dim_player"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_market_value")),
        sa.UniqueConstraint("player_id", "valued_on", "source", name="uq_market_value_point"),
    )
    op.create_index(
        "ix_market_value_player_date", "fact_market_value", ["player_id", "valued_on"], unique=False
    )
    op.create_table(
        "fact_player_season_stats",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("club_id", sa.String(length=64), nullable=True),
        sa.Column("competition_id", sa.String(length=64), nullable=False),
        sa.Column("season_id", sa.String(length=32), nullable=False),
        sa.Column("appearances", sa.Integer(), nullable=True),
        sa.Column("starts", sa.Integer(), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=True),
        sa.Column("goals", sa.Integer(), nullable=True),
        sa.Column("non_penalty_goals", sa.Integer(), nullable=True),
        sa.Column("assists", sa.Integer(), nullable=True),
        sa.Column("xg", sa.Float(), nullable=True),
        sa.Column("npxg", sa.Float(), nullable=True),
        sa.Column("xa", sa.Float(), nullable=True),
        sa.Column("shots", sa.Integer(), nullable=True),
        sa.Column("shots_on_target", sa.Integer(), nullable=True),
        sa.Column("penalties_taken", sa.Integer(), nullable=True),
        sa.Column("passes", sa.Integer(), nullable=True),
        sa.Column("passes_completed", sa.Integer(), nullable=True),
        sa.Column("progressive_passes", sa.Integer(), nullable=True),
        sa.Column("key_passes", sa.Integer(), nullable=True),
        sa.Column("crosses", sa.Integer(), nullable=True),
        sa.Column("accurate_crosses", sa.Integer(), nullable=True),
        sa.Column("dribbles", sa.Integer(), nullable=True),
        sa.Column("successful_dribbles", sa.Integer(), nullable=True),
        sa.Column("tackles", sa.Integer(), nullable=True),
        sa.Column("successful_tackles", sa.Integer(), nullable=True),
        sa.Column("interceptions", sa.Integer(), nullable=True),
        sa.Column("blocks", sa.Integer(), nullable=True),
        sa.Column("clearances", sa.Integer(), nullable=True),
        sa.Column("duels", sa.Integer(), nullable=True),
        sa.Column("duels_won", sa.Integer(), nullable=True),
        sa.Column("aerial_duels", sa.Integer(), nullable=True),
        sa.Column("aerial_duels_won", sa.Integer(), nullable=True),
        sa.Column("fouls_committed", sa.Integer(), nullable=True),
        sa.Column("fouls_drawn", sa.Integer(), nullable=True),
        sa.Column("dispossessed", sa.Integer(), nullable=True),
        sa.Column("dribbled_past", sa.Integer(), nullable=True),
        sa.Column("saves", sa.Integer(), nullable=True),
        sa.Column("inside_box_saves", sa.Integer(), nullable=True),
        sa.Column("goals_conceded", sa.Integer(), nullable=True),
        sa.Column("clean_sheets", sa.Integer(), nullable=True),
        sa.Column("penalties_saved", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "accurate_crosses IS NULL OR accurate_crosses >= 0",
            name=op.f("ck_fact_player_season_stats_accurate_crosses_non_negative"),
        ),
        sa.CheckConstraint(
            "aerial_duels IS NULL OR aerial_duels >= 0",
            name=op.f("ck_fact_player_season_stats_aerial_duels_non_negative"),
        ),
        sa.CheckConstraint(
            "aerial_duels IS NULL OR aerial_duels_won IS NULL OR aerial_duels_won <= aerial_duels",
            name=op.f("ck_fact_player_season_stats_aerial_duels_won_within_aerial_duels"),
        ),
        sa.CheckConstraint(
            "aerial_duels_won IS NULL OR aerial_duels_won >= 0",
            name=op.f("ck_fact_player_season_stats_aerial_duels_won_non_negative"),
        ),
        sa.CheckConstraint(
            "appearances IS NULL OR appearances >= 0",
            name=op.f("ck_fact_player_season_stats_appearances_non_negative"),
        ),
        sa.CheckConstraint(
            "appearances IS NULL OR minutes IS NULL OR minutes <= appearances * 120",
            name=op.f("ck_fact_player_season_stats_minutes_within_appearances"),
        ),
        sa.CheckConstraint(
            "assists IS NULL OR assists >= 0",
            name=op.f("ck_fact_player_season_stats_assists_non_negative"),
        ),
        sa.CheckConstraint(
            "blocks IS NULL OR blocks >= 0",
            name=op.f("ck_fact_player_season_stats_blocks_non_negative"),
        ),
        sa.CheckConstraint(
            "clean_sheets IS NULL OR clean_sheets >= 0",
            name=op.f("ck_fact_player_season_stats_clean_sheets_non_negative"),
        ),
        sa.CheckConstraint(
            "clearances IS NULL OR clearances >= 0",
            name=op.f("ck_fact_player_season_stats_clearances_non_negative"),
        ),
        sa.CheckConstraint(
            "crosses IS NULL OR crosses >= 0",
            name=op.f("ck_fact_player_season_stats_crosses_non_negative"),
        ),
        sa.CheckConstraint(
            "dispossessed IS NULL OR dispossessed >= 0",
            name=op.f("ck_fact_player_season_stats_dispossessed_non_negative"),
        ),
        sa.CheckConstraint(
            "dribbled_past IS NULL OR dribbled_past >= 0",
            name=op.f("ck_fact_player_season_stats_dribbled_past_non_negative"),
        ),
        sa.CheckConstraint(
            "dribbles IS NULL OR dribbles >= 0",
            name=op.f("ck_fact_player_season_stats_dribbles_non_negative"),
        ),
        sa.CheckConstraint(
            "duels IS NULL OR duels >= 0",
            name=op.f("ck_fact_player_season_stats_duels_non_negative"),
        ),
        sa.CheckConstraint(
            "duels IS NULL OR duels_won IS NULL OR duels_won <= duels",
            name=op.f("ck_fact_player_season_stats_duels_won_within_duels"),
        ),
        sa.CheckConstraint(
            "duels_won IS NULL OR duels_won >= 0",
            name=op.f("ck_fact_player_season_stats_duels_won_non_negative"),
        ),
        sa.CheckConstraint(
            "fouls_committed IS NULL OR fouls_committed >= 0",
            name=op.f("ck_fact_player_season_stats_fouls_committed_non_negative"),
        ),
        sa.CheckConstraint(
            "fouls_drawn IS NULL OR fouls_drawn >= 0",
            name=op.f("ck_fact_player_season_stats_fouls_drawn_non_negative"),
        ),
        sa.CheckConstraint(
            "goals IS NULL OR goals >= 0",
            name=op.f("ck_fact_player_season_stats_goals_non_negative"),
        ),
        sa.CheckConstraint(
            "goals IS NULL OR non_penalty_goals IS NULL OR non_penalty_goals <= goals",
            name=op.f("ck_fact_player_season_stats_non_penalty_goals_within_goals"),
        ),
        sa.CheckConstraint(
            "goals_conceded IS NULL OR goals_conceded >= 0",
            name=op.f("ck_fact_player_season_stats_goals_conceded_non_negative"),
        ),
        sa.CheckConstraint(
            "inside_box_saves IS NULL OR inside_box_saves >= 0",
            name=op.f("ck_fact_player_season_stats_inside_box_saves_non_negative"),
        ),
        sa.CheckConstraint(
            "interceptions IS NULL OR interceptions >= 0",
            name=op.f("ck_fact_player_season_stats_interceptions_non_negative"),
        ),
        sa.CheckConstraint(
            "key_passes IS NULL OR key_passes >= 0",
            name=op.f("ck_fact_player_season_stats_key_passes_non_negative"),
        ),
        sa.CheckConstraint(
            "minutes IS NULL OR minutes >= 0",
            name=op.f("ck_fact_player_season_stats_minutes_non_negative"),
        ),
        sa.CheckConstraint(
            "non_penalty_goals IS NULL OR non_penalty_goals >= 0",
            name=op.f("ck_fact_player_season_stats_non_penalty_goals_non_negative"),
        ),
        sa.CheckConstraint(
            "npxg IS NULL OR npxg >= 0", name=op.f("ck_fact_player_season_stats_npxg_non_negative")
        ),
        sa.CheckConstraint(
            "passes IS NULL OR passes >= 0",
            name=op.f("ck_fact_player_season_stats_passes_non_negative"),
        ),
        sa.CheckConstraint(
            "passes IS NULL OR passes_completed IS NULL OR passes_completed <= passes",
            name=op.f("ck_fact_player_season_stats_passes_completed_within_attempted"),
        ),
        sa.CheckConstraint(
            "passes_completed IS NULL OR passes_completed >= 0",
            name=op.f("ck_fact_player_season_stats_passes_completed_non_negative"),
        ),
        sa.CheckConstraint(
            "penalties_saved IS NULL OR penalties_saved >= 0",
            name=op.f("ck_fact_player_season_stats_penalties_saved_non_negative"),
        ),
        sa.CheckConstraint(
            "penalties_taken IS NULL OR penalties_taken >= 0",
            name=op.f("ck_fact_player_season_stats_penalties_taken_non_negative"),
        ),
        sa.CheckConstraint(
            "progressive_passes IS NULL OR progressive_passes >= 0",
            name=op.f("ck_fact_player_season_stats_progressive_passes_non_negative"),
        ),
        sa.CheckConstraint(
            "saves IS NULL OR saves >= 0",
            name=op.f("ck_fact_player_season_stats_saves_non_negative"),
        ),
        sa.CheckConstraint(
            "shots IS NULL OR shots >= 0",
            name=op.f("ck_fact_player_season_stats_shots_non_negative"),
        ),
        sa.CheckConstraint(
            "shots IS NULL OR shots_on_target IS NULL OR shots_on_target <= shots",
            name=op.f("ck_fact_player_season_stats_shots_on_target_within_shots"),
        ),
        sa.CheckConstraint(
            "shots_on_target IS NULL OR shots_on_target >= 0",
            name=op.f("ck_fact_player_season_stats_shots_on_target_non_negative"),
        ),
        sa.CheckConstraint(
            "starts IS NULL OR starts >= 0",
            name=op.f("ck_fact_player_season_stats_starts_non_negative"),
        ),
        sa.CheckConstraint(
            "successful_dribbles IS NULL OR successful_dribbles >= 0",
            name=op.f("ck_fact_player_season_stats_successful_dribbles_non_negative"),
        ),
        sa.CheckConstraint(
            "successful_tackles IS NULL OR successful_tackles >= 0",
            name=op.f("ck_fact_player_season_stats_successful_tackles_non_negative"),
        ),
        sa.CheckConstraint(
            "tackles IS NULL OR tackles >= 0",
            name=op.f("ck_fact_player_season_stats_tackles_non_negative"),
        ),
        sa.CheckConstraint(
            "xa IS NULL OR xa >= 0", name=op.f("ck_fact_player_season_stats_xa_non_negative")
        ),
        sa.CheckConstraint(
            "xg IS NULL OR xg >= 0", name=op.f("ck_fact_player_season_stats_xg_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["dim_club.club_id"],
            name=op.f("fk_fact_player_season_stats_club_id_dim_club"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["dim_competition.competition_id"],
            name=op.f("fk_fact_player_season_stats_competition_id_dim_competition"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["dim_player.player_id"],
            name=op.f("fk_fact_player_season_stats_player_id_dim_player"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["dim_season.season_id"],
            name=op.f("fk_fact_player_season_stats_season_id_dim_season"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_player_season_stats")),
        sa.UniqueConstraint(
            "player_id", "competition_id", "season_id", name="uq_player_competition_season"
        ),
    )
    op.create_index(
        "ix_stats_competition_season",
        "fact_player_season_stats",
        ["competition_id", "season_id"],
        unique=False,
    )
    op.create_index("ix_stats_minutes", "fact_player_season_stats", ["minutes"], unique=False)
    op.create_index(
        "ix_stats_player_season",
        "fact_player_season_stats",
        ["player_id", "season_id"],
        unique=False,
    )
    op.create_table(
        "fact_transfer",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("transfer_date", sa.Date(), nullable=True),
        sa.Column("season", sa.String(length=16), nullable=True),
        sa.Column("from_club_id", sa.String(length=64), nullable=True),
        sa.Column("to_club_id", sa.String(length=64), nullable=True),
        sa.Column("from_club_name", sa.Text(), nullable=True),
        sa.Column("to_club_name", sa.Text(), nullable=True),
        sa.Column("fee_eur", sa.BigInteger(), nullable=True),
        sa.Column("market_value_at_transfer_eur", sa.BigInteger(), nullable=True),
        sa.Column(
            "transfer_type",
            sa.Enum(
                "permanent",
                "loan",
                "loan_end",
                "free",
                "youth",
                "retired",
                "unknown",
                name="transfer_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "fee_eur IS NULL OR fee_eur >= 0", name=op.f("ck_fact_transfer_fee_non_negative")
        ),
        sa.CheckConstraint(
            "market_value_at_transfer_eur IS NULL OR market_value_at_transfer_eur >= 0",
            name=op.f("ck_fact_transfer_transfer_market_value_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["from_club_id"],
            ["dim_club.club_id"],
            name=op.f("fk_fact_transfer_from_club_id_dim_club"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["dim_player.player_id"],
            name=op.f("fk_fact_transfer_player_id_dim_player"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_club_id"],
            ["dim_club.club_id"],
            name=op.f("fk_fact_transfer_to_club_id_dim_club"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_transfer")),
    )
    op.create_index(
        "ix_transfer_player_date", "fact_transfer", ["player_id", "transfer_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transfer_player_date", table_name="fact_transfer")
    op.drop_table("fact_transfer")
    op.drop_index("ix_stats_player_season", table_name="fact_player_season_stats")
    op.drop_index("ix_stats_minutes", table_name="fact_player_season_stats")
    op.drop_index("ix_stats_competition_season", table_name="fact_player_season_stats")
    op.drop_table("fact_player_season_stats")
    op.drop_index("ix_market_value_player_date", table_name="fact_market_value")
    op.drop_table("fact_market_value")
    op.drop_index("ix_bridge_player", table_name="bridge_player_source")
    op.drop_table("bridge_player_source")
    op.drop_index("ix_dim_player_recruitment", table_name="dim_player")
    op.drop_index("ix_dim_player_position_group", table_name="dim_player")
    op.drop_index("ix_dim_player_normalized_name", table_name="dim_player")
    op.drop_index("ix_dim_player_market_value", table_name="dim_player")
    op.drop_index("ix_dim_player_dob", table_name="dim_player")
    op.drop_index("ix_dim_player_competition", table_name="dim_player")
    op.drop_index("ix_dim_player_club", table_name="dim_player")
    op.drop_table("dim_player")
    op.drop_index("ix_dim_club_name", table_name="dim_club")
    op.drop_index("ix_dim_club_competition", table_name="dim_club")
    op.drop_table("dim_club")
    op.drop_index("ix_data_quality_executed", table_name="fact_data_quality")
    op.drop_table("fact_data_quality")
    op.drop_table("dim_season")
    op.drop_index("ix_dim_competition_country", table_name="dim_competition")
    op.drop_table("dim_competition")
    # ### end Alembic commands ###
