"""user accounts and sessions

Revision ID: 0003_accounts
Revises: 0002_analytical_schema
Create Date: 2026-08-27 18:05:01.451908
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003_accounts"
down_revision: str | None = "0002_analytical_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account",
        sa.Column("user_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "email = lower(email)", name=op.f("ck_user_account_email_is_normalised")
        ),
        sa.CheckConstraint("length(email) >= 3", name=op.f("ck_user_account_email_plausible")),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_account")),
        sa.UniqueConstraint("email", name="uq_user_account_email"),
    )
    op.create_table(
        "user_session",
        sa.Column("session_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_user_session_session_expiry_after_creation")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.user_id"],
            name=op.f("fk_user_session_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_user_session")),
        sa.UniqueConstraint("token_hash", name="uq_user_session_token"),
    )
    op.create_index("ix_user_session_expiry", "user_session", ["expires_at"], unique=False)
    op.create_index("ix_user_session_user", "user_session", ["user_id"], unique=False)
    op.drop_constraint(
        op.f("ck_fact_player_season_stats_aerial_duels_won_within_aer_c6d9"),
        "fact_player_season_stats",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_fact_player_season_stats_aerial_duels_won_within_aerial_duels"),
        "fact_player_season_stats",
        "aerial_duels IS NULL OR aerial_duels_won IS NULL OR aerial_duels_won <= aerial_duels",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_fact_player_season_stats_aerial_duels_won_within_aerial_duels"),
        "fact_player_season_stats",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_fact_player_season_stats_aerial_duels_won_within_aer_c6d9"),
        "fact_player_season_stats",
        "aerial_duels IS NULL OR aerial_duels_won IS NULL OR aerial_duels_won <= aerial_duels",
    )
    op.drop_index("ix_user_session_user", table_name="user_session")
    op.drop_index("ix_user_session_expiry", table_name="user_session")
    op.drop_table("user_session")
    op.drop_table("user_account")
    # ### end Alembic commands ###
