"""recorded minutes

Splits "time on the pitch" from "the minutes the statistics cover".

Measured against the real FootyStats API: detailed statistics are recorded for
only some matches, and a season total divided by *all* minutes played
understates the rate in exact proportion to the gap. 87% of player-seasons in
the sample had full coverage; the worst had 82 recorded minutes against 303
played, where a per-90 over total minutes reports 27% of the true value with
nothing to indicate anything is wrong.

Nullable, because a provider that does not distinguish the two leaves it unset
and the metrics engine falls back to `minutes`.

Revision ID: 0005_recorded_minutes
Revises: 0004_shortlists
Create Date: 2026-08-29 18:52:11.016782
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005_recorded_minutes"
down_revision: str | None = "0004_shortlists"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fact_player_season_stats", sa.Column("recorded_minutes", sa.Integer(), nullable=True)
    )
    op.create_check_constraint(
        op.f("ck_fact_player_season_stats_recorded_minutes_non_negative"),
        "fact_player_season_stats",
        "recorded_minutes IS NULL OR recorded_minutes >= 0",
    )
    op.create_check_constraint(
        op.f("ck_fact_player_season_stats_recorded_minutes_within_minutes"),
        "fact_player_season_stats",
        "recorded_minutes IS NULL OR minutes IS NULL OR recorded_minutes <= minutes",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_fact_player_season_stats_recorded_minutes_within_minutes"),
        "fact_player_season_stats",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_fact_player_season_stats_recorded_minutes_non_negative"),
        "fact_player_season_stats",
        type_="check",
    )
    op.drop_column("fact_player_season_stats", "recorded_minutes")
    # ### end Alembic commands ###
