"""Run identity resolution and report on it.

From the repository root:
    python -m pipelines.identity_resolution.run

Runs two things, because either alone would be misleading:

1. **Mock performance players against Transfermarkt.** Their names are invented,
   so every correct answer is "no match". Any match here is a false positive,
   which makes this a direct measure of whether the resolver invents links.

2. **A perturbed shadow of Transfermarkt against Transfermarkt.** Ground truth
   is known by construction, so precision and recall are measurable.

Writes `docs/identity_resolution_report.md` and prints the matched / unmatched /
ambiguous / manual-review breakdown the spec asks for. Nothing is written to the
database: this phase decides *how* resolution behaves, and inspecting that comes
before acting on it.
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import Counter
from pathlib import Path

from app.providers.mock import MockPerformanceProvider
from app.providers.transfermarkt import TransfermarktDatasetProvider
from pipelines.identity_resolution.evaluate import evaluate_against_shadow
from pipelines.identity_resolution.matcher import (
    DEFAULT_THRESHOLD,
    Identity,
    IdentityResolver,
    MatchResult,
    MatchStatus,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"
MANUAL_MAPPING = REPO_ROOT / "data" / "manual" / "player_mapping.csv"
SEASON = "2026-2027"


def load_manual_overrides(path: Path = MANUAL_MAPPING) -> dict[tuple[str, str], str]:
    """Read human-confirmed mappings.

    These win over anything the resolver decides. A person who has checked a
    pair should never have their decision overwritten by a later automated run.
    """
    if not path.exists():
        return {}
    overrides: dict[tuple[str, str], str] = {}
    with path.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            if not row.get("source") or row["source"].lstrip().startswith("#"):
                continue
            source = row["source"].strip()
            source_id = (row.get("source_player_id") or "").strip()
            target_id = (row.get("target_player_id") or "").strip()
            if source and source_id and target_id:
                overrides[(source, source_id)] = target_id
    return overrides


def transfermarkt_identities(provider: TransfermarktDatasetProvider) -> list[Identity]:
    clubs = {c.source_club_id: c.name for c in provider.get_clubs()}
    return [
        Identity(
            source="transfermarkt",
            source_player_id=player.source_player_id,
            full_name=player.full_name,
            date_of_birth=player.date_of_birth,
            nationality=player.nationality,
            club_name=clubs.get(player.current_club_id or ""),
            position_group=player.position_group,
        )
        for player in provider.get_players()
    ]


def mock_identities(provider: MockPerformanceProvider) -> list[Identity]:
    identities: list[Identity] = []
    for competition in provider.get_competitions():
        clubs = {c.club_id: c.name for c in provider.get_clubs(competition.competition_id, SEASON)}
        for player in provider.get_players(competition.competition_id, SEASON):
            identities.append(
                Identity(
                    source="demo",
                    source_player_id=player.source_player_id,
                    full_name=player.full_name,
                    date_of_birth=player.date_of_birth,
                    nationality=player.nationality,
                    club_name=clubs.get(player.club_id),
                    position_group=player.position_group,
                )
            )
    return identities


def summarise(results: list[MatchResult]) -> Counter[str]:
    return Counter(result.status.value for result in results)


def _render_report(
    threshold: float,
    target_count: int,
    mock_results: list[MatchResult],
    shadow_evaluation,
    shadow_results: list[MatchResult],
    manual_count: int,
) -> str:
    mock_summary = summarise(mock_results)
    method_counts = Counter(r.method for r in shadow_results if r.status is MatchStatus.MATCHED)

    out: list[str] = []
    out.append("# Identity resolution report\n")
    out.append(
        "Generated by `python -m pipelines.identity_resolution.run`. Do not edit by hand.\n\n"
        f"Auto-match threshold **{threshold:.2f}**, target set **{target_count:,}** "
        "Transfermarkt identities.\n\n"
        "Resolution never matches on name alone. A name is one signal alongside date of "
        "birth, nationality, club and position, and on its own it cannot reach the "
        "threshold whatever its similarity.\n"
    )

    out.append("\n## Why two runs\n")
    out.append(
        "A wrong match is worse than no match: an unmatched player is visibly missing, "
        "while a wrongly matched one silently attaches somebody else's statistics to a "
        "real person's profile. The two runs below measure the two failure modes "
        "separately.\n"
    )

    out.append("\n## Run 1 — mock performance players against Transfermarkt\n")
    out.append(
        "Mock player names are invented, so the correct answer for every one of them is "
        "**no match**. Anything matched here is a false positive.\n"
    )
    out.append("| Outcome | Count |")
    out.append("| --- | --- |")
    for status in MatchStatus:
        out.append(f"| {status.value} | {mock_summary.get(status.value, 0):,} |")
    false_positives = mock_summary.get("matched", 0)
    verdict = (
        "**0 false positives**"
        if false_positives == 0
        else f"**{false_positives} false positives**"
    )
    out.append(f"\nResult: {verdict}.\n")

    out.append("\n## Run 2 — perturbed shadow against Transfermarkt\n")
    out.append(
        "Real identities are copied and degraded the way a second provider would differ: "
        "name order swapped, middle names dropped, playing name instead of registered "
        "name, occasional typos, and missing birth date, nationality or club. Ground "
        "truth is known by construction.\n\n"
        "Some records are unresolvable by design — a surname alone with no birth date "
        "cannot be pinned to one person — so recall below 100% is the correct outcome, "
        "not a defect. Those records belong in manual review.\n"
    )
    out.append("```")
    out.append(shadow_evaluation.render())
    out.append("```\n")

    out.append("\n### Which rule decided each match\n")
    out.append("| Method | Matches |")
    out.append("| --- | --- |")
    for method, count in method_counts.most_common():
        out.append(f"| `{method}` | {count:,} |")

    out.append("\n## Manual review queue\n")
    ambiguous = [r for r in shadow_results if r.status is MatchStatus.AMBIGUOUS]
    out.append(
        f"{len(ambiguous):,} pairs were **ambiguous**: a best candidate that cleared the "
        "threshold but was too close to its runner-up to separate them. These are "
        "reported rather than resolved by taking the higher score, which would be "
        "arbitrary.\n"
    )
    if ambiguous:
        out.append("\nExamples:\n")
        out.append("| Source name | Best candidate | Best | Runner-up |")
        out.append("| --- | --- | --- | --- |")
        for result in ambiguous[:10]:
            runner = result.runner_up.full_name if result.runner_up else "-"
            out.append(
                f"| {result.source.full_name} | {runner} | "
                f"{result.confidence:.2f} | {result.runner_up_confidence:.2f} |"
            )

    out.append("\n## Manual overrides\n")
    out.append(
        f"{manual_count} mapping(s) are currently confirmed by hand in "
        "`data/manual/player_mapping.csv`. A manual mapping always wins over an "
        "automated decision and is recorded with `manual_override = true`, so a "
        "re-run cannot quietly reverse a human judgement.\n"
    )
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run identity resolution and report.")
    parser.add_argument("--threshold", type=float, default=DEFAULT_THRESHOLD)
    parser.add_argument("--sample", type=int, default=2000, help="shadow records to evaluate")
    args = parser.parse_args(argv)

    provider = TransfermarktDatasetProvider()
    targets = transfermarkt_identities(provider)
    overrides = load_manual_overrides()

    print(f"targets            {len(targets):,} Transfermarkt identities")
    print(f"manual overrides   {len(overrides)}")
    print(f"threshold          {args.threshold:.2f}\n")

    print("RUN 1 - mock performance players (every correct answer is 'no match')")
    resolver = IdentityResolver(targets, threshold=args.threshold, manual_overrides=overrides)
    mock_results = resolver.resolve_all(mock_identities(MockPerformanceProvider()))
    mock_summary = summarise(mock_results)
    for status in MatchStatus:
        print(f"  {status.value:<12} {mock_summary.get(status.value, 0):>7,}")
    false_positives = mock_summary.get("matched", 0)
    print(
        f"  -> {'no false positives' if not false_positives else f'{false_positives} FALSE POSITIVES'}\n"
    )

    print(f"RUN 2 - perturbed shadow of {args.sample:,} real identities (ground truth known)")
    evaluation, shadow_results, _ = evaluate_against_shadow(
        targets, sample=args.sample, threshold=args.threshold
    )
    print(evaluation.render())

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = DOCS_DIR / "identity_resolution_report.md"
    report_path.write_text(
        _render_report(
            args.threshold, len(targets), mock_results, evaluation, shadow_results, len(overrides)
        ),
        encoding="utf-8",
    )
    print(f"\nwrote {report_path.relative_to(REPO_ROOT)}")

    # A false positive against invented names, or any incorrect match against
    # known truth, is a correctness failure rather than a tuning question.
    if false_positives or evaluation.incorrect:
        print("\nFAILED: the resolver produced matches known to be wrong.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
