"""Transfermarkt dataset provider.

Reads the extracted snapshot of https://github.com/dcaribou/transfermarkt-datasets
(CC0-1.0). The Transfermarkt website is never scraped, and the raw snapshot is
never redistributed.

Every field mapped here was verified against the real files first; see
`docs/transfermarkt_field_availability.md`, generated by
`python -m pipelines.transfermarkt.profile`. Two attributes the master spec
expects are genuinely absent, and are left absent rather than approximated:

- **transfer type** — the transfers table has no type column. Loans, permanent
  moves and free transfers are indistinguishable. Fee cannot stand in for it:
  96,085 rows carry a fee of 0 and 61,526 carry none, and neither pattern
  identifies a loan. Every record is typed UNKNOWN.
- **secondary nationality** — only citizenship and country of birth exist, and
  country of birth is a different fact. The field stays empty.

Bad source values are quarantined, not corrected and not fatal: a player with a
height of 18cm loses the height and keeps the rest of their record, and the
rejection is recorded in `quality_issues()`.
"""

from __future__ import annotations

import json
from datetime import date, datetime
from functools import cached_property
from pathlib import Path
from typing import Any

import yaml

from app.core import paths
from app.core.logging import get_logger
from app.providers.market_base import (
    DataQualityIssue,
    MarketDataProvider,
    MarketDataUnavailableError,
)
from app.schemas.canonical import PositionGroup, PreferredFoot
from app.schemas.market import (
    MarketClub,
    MarketCompetition,
    MarketPlayer,
    MarketProviderInfo,
    MarketValuePoint,
    TransferRecord,
    TransferType,
    normalize_name,
)

log = get_logger(__name__)

REPO_ROOT = paths.REPO_ROOT
DEFAULT_TABLES_DIR = REPO_ROOT / "data" / "raw" / "transfermarkt" / "tables"
DEFAULT_MANIFEST = (
    REPO_ROOT / "data" / "raw" / "transfermarkt" / "transfermarkt-datasets.manifest.json"
)
POSITION_MAPPING_PATH = REPO_ROOT / "config" / "position_mapping.yaml"

REQUIRED_TABLES = ("players", "clubs", "competitions", "player_valuations", "transfers")

SOURCE_URL = "https://github.com/dcaribou/transfermarkt-datasets"
LICENCE = "CC0-1.0"

# A height outside this range is a data entry error, not a footballer.
MIN_HEIGHT_CM = 140
MAX_HEIGHT_CM = 220

# Placeholder the source writes instead of a null.
MISSING_LABEL = "Missing"

_FOOT_MAP = {
    "right": PreferredFoot.RIGHT,
    "left": PreferredFoot.LEFT,
    "both": PreferredFoot.BOTH,
}


def _load_position_mapping(path: Path = POSITION_MAPPING_PATH) -> dict[str, PositionGroup]:
    """Load the verified sub_position mapping from config.

    Kept in config rather than code so the mapping can be reviewed and amended
    without touching the provider, per spec section 31 rule 5.
    """
    if not path.exists():
        raise MarketDataUnavailableError(f"Position mapping not found: {path}")
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    mapping = (raw.get("transfermarkt") or {}).get("sub_position") or {}
    return {label: PositionGroup(group) for label, group in mapping.items()}


def _as_date(value: Any) -> date | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    return None


def _as_int(value: Any) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _clean(value: Any) -> str | None:
    """Normalise a source string, treating blanks and the 'Missing' placeholder
    as absent."""
    if value is None:
        return None
    text = str(value).strip()
    if not text or text == MISSING_LABEL:
        return None
    return text


class TransfermarktDatasetProvider(MarketDataProvider):
    """Market data from a local snapshot of the public Transfermarkt dataset."""

    def __init__(
        self,
        *,
        tables_dir: Path = DEFAULT_TABLES_DIR,
        manifest_path: Path = DEFAULT_MANIFEST,
        position_mapping_path: Path = POSITION_MAPPING_PATH,
    ) -> None:
        self._tables_dir = tables_dir
        self._manifest_path = manifest_path
        self._position_mapping = _load_position_mapping(position_mapping_path)
        self._issues: list[DataQualityIssue] = []

        missing = [t for t in REQUIRED_TABLES if not self._table_path(t).exists()]
        if missing:
            raise MarketDataUnavailableError(
                "Transfermarkt snapshot is incomplete; missing tables: "
                f"{', '.join(missing)}. Run: python -m pipelines.transfermarkt.download"
            )

    # -- Infrastructure ------------------------------------------------------

    def _table_path(self, name: str) -> Path:
        return self._tables_dir / f"{name}.csv.gz"

    @cached_property
    def _con(self) -> Any:
        """In-memory DuckDB with each table materialised.

        Materialised rather than left as views over the gzipped CSVs: a view
        re-decompresses and rescans on every query, which turns a per-player
        lookup over 656,301 valuations into a full file scan.
        """
        import duckdb

        con = duckdb.connect()
        for name in REQUIRED_TABLES:
            # DuckDB cannot parameterise a table name or a file path in DDL.
            # `name` comes only from the REQUIRED_TABLES constant, never from a
            # caller; the assertion keeps that true if the loop is ever changed.
            if name not in REQUIRED_TABLES:  # pragma: no cover - defensive
                raise ValueError(f"table not in allowlist: {name}")
            path = self._table_path(name).as_posix()
            con.execute(
                # S608: `name` is from the REQUIRED_TABLES allowlist, never a
                # caller. DuckDB cannot parameterise a table name or file path.
                f"CREATE TABLE {name} AS SELECT * FROM read_csv_auto('{path}')"  # noqa: S608
            )
        con.execute("CREATE INDEX idx_val_player ON player_valuations(player_id)")
        con.execute("CREATE INDEX idx_tr_player ON transfers(player_id)")
        log.info("transfermarkt_snapshot_loaded", tables=len(REQUIRED_TABLES))
        return con

    @cached_property
    def _snapshot_date(self) -> date | None:
        if not self._manifest_path.exists():
            return None
        try:
            manifest = json.loads(self._manifest_path.read_text(encoding="utf-8"))
            return datetime.fromisoformat(manifest["retrieved_at"]).date()
        except (ValueError, KeyError, OSError):
            return None

    @property
    def info(self) -> MarketProviderInfo:
        return MarketProviderInfo(
            name="TransfermarktDatasetProvider",
            is_mock=False,
            # The schema HAS been profiled and the mapping written against it,
            # which is exactly what this flag is for.
            validated=True,
            snapshot_date=self._snapshot_date,
            licence=LICENCE,
            source_url=SOURCE_URL,
            notes=(
                "Public dataset snapshot. Transfer type and secondary nationality are "
                "not carried by this source and are left unset."
            ),
        )

    def quality_issues(self) -> list[DataQualityIssue]:
        return list(self._issues)

    def _record(self, entity: str, entity_id: str, field: str, raw: object, reason: str) -> None:
        self._issues.append(DataQualityIssue(entity, entity_id, field, raw, reason))

    # -- Reads ---------------------------------------------------------------

    @cached_property
    def _competition_country(self) -> dict[str, str | None]:
        rows = self._con.execute("SELECT competition_id, country_name FROM competitions").fetchall()
        return {str(cid): _clean(country) for cid, country in rows}

    def get_competitions(self) -> list[MarketCompetition]:
        rows = self._con.execute(
            "SELECT competition_id, name, country_name, type FROM competitions"
        ).fetchall()
        return [
            MarketCompetition(
                source_competition_id=str(cid),
                name=str(name),
                country=_clean(country),
                tier=_clean(comp_type),
            )
            for cid, name, country, comp_type in rows
        ]

    def get_clubs(self) -> list[MarketClub]:
        """Clubs, with country derived from their domestic competition.

        The clubs table carries no country column; joining through
        `domestic_competition_id` is a derivation, not a substitution.
        """
        rows = self._con.execute(
            "SELECT club_id, name, domestic_competition_id FROM clubs"
        ).fetchall()
        return [
            MarketClub(
                source_club_id=str(club_id),
                name=str(name),
                source_competition_id=_clean(competition_id),
                country=self._competition_country.get(str(competition_id)),
            )
            for club_id, name, competition_id in rows
        ]

    def get_players(self, *, competition_id: str | None = None) -> list[MarketPlayer]:
        sql = """
            SELECT player_id, name, date_of_birth, country_of_citizenship, foot,
                   height_in_cm, position, sub_position, contract_expiration_date,
                   current_club_id, current_club_domestic_competition_id,
                   market_value_in_eur
            FROM players
        """
        params: list[Any] = []
        if competition_id is not None:
            sql += " WHERE current_club_domestic_competition_id = ?"
            params.append(competition_id)

        return [self._map_player(row) for row in self._con.execute(sql, params).fetchall()]

    def _map_player(self, row: tuple[Any, ...]) -> MarketPlayer:
        (
            player_id,
            name,
            dob,
            citizenship,
            foot,
            height,
            position,
            sub_position,
            contract,
            club_id,
            competition_id,
            market_value,
        ) = row
        pid = str(player_id)
        display_name = str(name) if name else ""

        # Height: reject the impossible, keep the player.
        height_cm = _as_int(height)
        if height_cm is not None and not (MIN_HEIGHT_CM <= height_cm <= MAX_HEIGHT_CM):
            self._record(
                "player",
                pid,
                "height_in_cm",
                height_cm,
                f"outside {MIN_HEIGHT_CM}-{MAX_HEIGHT_CM}cm; treated as unknown",
            )
            height_cm = None

        raw_sub_position = _clean(sub_position)
        position_group = self._position_mapping.get(raw_sub_position) if raw_sub_position else None
        if raw_sub_position and position_group is None:
            # An unseen label must not be forced into the nearest group.
            self._record(
                "player",
                pid,
                "sub_position",
                raw_sub_position,
                "label not present in config/position_mapping.yaml; group left unset",
            )

        foot_value = _clean(foot)
        preferred_foot = _FOOT_MAP.get(foot_value.lower()) if foot_value else None
        if foot_value and preferred_foot is None:
            self._record("player", pid, "foot", foot_value, "unrecognised value")

        return MarketPlayer(
            source_player_id=pid,
            full_name=display_name,
            normalized_name=normalize_name(display_name),
            date_of_birth=_as_date(dob),
            nationality=_clean(citizenship),
            # Not carried by this source. country_of_birth is a different fact
            # and is deliberately not substituted here.
            secondary_nationality=None,
            preferred_foot=preferred_foot,
            height_cm=height_cm,
            raw_position=_clean(position),
            raw_sub_position=raw_sub_position,
            position_group=position_group,
            current_club_id=_clean(club_id),
            current_competition_id=_clean(competition_id),
            market_value_eur=_as_int(market_value),
            contract_expires=_as_date(contract),
        )

    def get_market_value_history(self, source_player_id: str) -> list[MarketValuePoint]:
        rows = self._con.execute(
            """
            SELECT date, market_value_in_eur, current_club_id,
                   player_club_domestic_competition_id
            FROM player_valuations
            WHERE player_id = ?
            ORDER BY date
            """,
            [int(source_player_id)] if source_player_id.isdigit() else [source_player_id],
        ).fetchall()

        points: list[MarketValuePoint] = []
        for valued_on, value, club_id, competition_id in rows:
            day, amount = _as_date(valued_on), _as_int(value)
            if day is None or amount is None:
                continue
            points.append(
                MarketValuePoint(
                    source_player_id=source_player_id,
                    valued_on=day,
                    market_value_eur=amount,
                    source_club_id=_clean(club_id),
                    source_competition_id=_clean(competition_id),
                )
            )
        return points

    def get_transfers(self, source_player_id: str) -> list[TransferRecord]:
        rows = self._con.execute(
            """
            SELECT transfer_date, transfer_season, from_club_id, from_club_name,
                   to_club_id, to_club_name, transfer_fee, market_value_in_eur
            FROM transfers
            WHERE player_id = ?
            ORDER BY transfer_date
            """,
            [int(source_player_id)] if source_player_id.isdigit() else [source_player_id],
        ).fetchall()

        return [
            TransferRecord(
                source_player_id=source_player_id,
                transfer_date=_as_date(transfer_date),
                season=_clean(season),
                from_club_id=_clean(from_id),
                from_club_name=_clean(from_name),
                to_club_id=_clean(to_id),
                to_club_name=_clean(to_name),
                # 0 and None mean different things here: 0 is a reported free
                # transfer, None is a fee the source does not carry. Collapsing
                # them would invent information.
                fee_eur=_as_int(fee),
                market_value_at_transfer_eur=_as_int(value_at_transfer),
                # Not derivable from this source; see the module docstring.
                transfer_type=TransferType.UNKNOWN,
            )
            for (
                transfer_date,
                season,
                from_id,
                from_name,
                to_id,
                to_name,
                fee,
                value_at_transfer,
            ) in rows
        ]
